server:
  port: 9030

spring:

  security:
    user:
      password: security_test

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security_test?characterEncoding=UTF-8&serverTimezone=UTC
    username: security
    password: security1234

  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        # ? ?? ??? Camel Case -> Snake Case ? ????? ??? ??
        # hibernate naming ????.
        # ? ???? ???, ?? ??? ??? ??? ???? ???? ?? ???? ??? ? ???? ??? ???? ?? ????.
        # Camel Case -> Snake Case <<< ?????? ???? ???? camel case -> snake_case ?? ???
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
    open-in-view: false
#    database: MYSQL
    database-platform: org.hibernate.dialect.MariaDB103Dialect # DB Dialect(??) ??
#    generate-ddl: false




